### PR TITLE
Parsing Tests and Bug Fixes

### LINKED ISSUE #45: Unit tests for arg parsing
Implement several test cases for argument parsing and add checks to cmake infrastructure. Add new executables in a test/ directory that return EXIT_SUCCESS/EXIT_FAILURE and then tell cmake where the test directory is.

### PR DESCRIPTION
**Pull request by woodjamesdee**
Contains comprehensive tests for all benchmark configuration command-line options for Spatter. Also fixes a few bugs that went unnoticed. Resolves #45.

### CODE REVIEW

File: tests/parse_ms1_suite.c [hunk 1]
```diff
@@ -0,0 +1,128 @@
...
+int ms1_test(int indexLength, int gapLocationCount, int* gapLocations, int gapSizeCount, int* gapSizes, int argc, char** argv)
+{
+    int nrc = 0; 
+    struct run_config *rc = NULL;
+
+    parse_args(argc, argv, &nrc, &rc);
+
+    if (nrc != 1)
+    {
+        printf("Test failure on Uniform Stride: Expected number of runs to be 1, actually was %d.\n", nrc);
```
Comment (plavin) [inline tests/parse_ms1_suite.c:35]: Uniform stride -> MS1

File: tests/parse_ms1_suite.c [hunk 2]
```diff
@@ -0,0 +1,128 @@
...
+        return EXIT_FAILURE;
+    }
+
+    if (rc == NULL)
+    {
+        printf("Test failure on Uniform Stride: failed to create or allocate run_config struct.\n");
```
Comment (plavin) [inline tests/parse_ms1_suite.c:41]: Same as above
